Updated TS definitions
i18next/react-i18next pull request #1247
Opened 2021-02-02 14:47 UTC by depoulo

#778 had forgotten the HOC

#### Checklist

- [ ] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

2021-02-03 07:55 UTC, jamuhl commented
@pedrodurek can you have a look?

2021-02-03 15:53 UTC, pedrodurek requested changes

2021-02-03 15:53 UTC, pedrodurek commented on src/ts4.1/index.d.ts
> +  props: TranslationProps<N> & { useSuspense?: boolean },
Hey @depoulo, thanks for your contribution. 
`src/index.d.ts` is right, but here we should place `useSuspense` under TranslationProps.

2021-02-08 15:05 UTC, pedrodurek approved these changes

2021-02-09 06:38 UTC, merged

2021-02-09 06:43 UTC, jamuhl commented
thanks to all helping with this PR - published in react-i18next@11.8.6